apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broadcast-role-binding
  namespace: broadcast-system
  labels:
    app: broadcast-microservice
subjects:
- kind: ServiceAccount
  name: broadcast-service-account
  namespace: broadcast-system
roleRef:
  kind: Role
  name: broadcast-role
  apiGroup: rbac.authorization.k8s.io