apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: broadcast-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          # Points to the Zookeeper service you created above
          value: "zookeeper-service:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          # Tells clients to connect via the Kafka service name
          value: "PLAINTEXT://kafka-service:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"