apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strimzi-cluster-operator-global
  labels:
    app: strimzi
rules:
  # This rule is the one that was failing
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "create"
      - "update"
      - "delete"
  # Add other necessary permissions
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "services"
      - "configmaps"
      - "secrets"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "delete"
      - "patch"
      - "update"