sequenceDiagram
    autonumber

    participant UserUI
    participant UserService as User Service
    participant GeodeInboxCache as Geode (user-messages-inbox)
    participant GeodeContentCache as Geode (broadcast-content)
    participant DB as PostgreSQL DB

    UserUI->>+UserService: 1- GET /api/user/messages

    UserService->>+GeodeInboxCache: 2- Get cached inbox for user
    
    alt Cache Hit
        GeodeInboxCache-->>-UserService: 3a- Returns List<UserMessageInbox>
        note right of UserService: 4a- Reconstruct full response DTOs...
        UserService->>+GeodeContentCache: 5a- Batch GET for all broadcastId's
        GeodeContentCache-->>-UserService: 
        UserService-->>-UserUI: 6a- Returns reconstructed inbox from cache
    else Cache Miss
        GeodeInboxCache-->>-UserService: 3b- Returns null
        UserService->>+DB: 4b- Query DB for all unread messages
        DB-->>-UserService: 5b- Returns user message list
        note right of UserService: 6b- Assemble full response DTOs...
        UserService->>+GeodeInboxCache: 7b- PUT lightweight inbox list into cache
        GeodeInboxCache-->>-UserService: 
        UserService-->>-UserUI: 8b- Returns newly assembled inbox
    end