sequenceDiagram
    participant Kafka as Kafka Broker
    participant ReceiverPod as User Service (Receiver Pod)
    participant Redis as Redis Pub/Sub Channel <br/> (sse-notifications)
    participant OtherPods as Other User Service Pods
    participant SsePod as User Service (SSE Pod)
    participant UserUI as User UI (Browser)

    Kafka->>+ReceiverPod: 1- Delivers user-specific action <br/> for "user-123"

    Note over ReceiverPod: Performs stateless work (e.g., cache cleanup)

    ReceiverPod->>+Redis: 2- PUBLISH notification to channel <br/> { userId: "user-123", ... }
    Redis-->>-ReceiverPod: Redis publish to receiver pod

    Note over Redis, OtherPods: Redis broadcasts the notification to ALL subscribers

    Redis->>+OtherPods: 3- Receives notification
    Note over OtherPods: Checks its in-memory SSE connections. <br/> No match found for "user-123". <br/> Discards message.
    OtherPods-->>-Redis: other pods conencts to redis
    
    Redis->>+SsePod: 3- Receives notification
    Note over SsePod: Checks its in-memory SSE connections. <br/> Match found for "user-123"!
    SsePod->>+UserUI: 4- Pushes real-time SSE event
    UserUI-->>-SsePod: user ui connects to sse pod