spring:
  config:
    import: "classpath:shared-config.yml"
  application:
    name: broadcast-admin-service # Admin service name
  # SQL Initialization for schema and data (Admin service needs to create schema)
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

server:
  port: 8081 # Admin service port
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystore.p12"
    key-store-password: "password"
    key-alias: "netty"

# Log file name is service-specific
logging:
  file:
    name: logs/broadcast-admin-service.log

# Resilience4j Rate Limiter is specific to the admin service's create endpoint
resilience4j:
  ratelimiter:
    instances:
      createBroadcastLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0
        registerHealthIndicator: true

# Custom properties unique to the admin service
broadcast:
  service:
    name: broadcast-admin-service
  h2-console:
    web-port: "8084" # Admin H2 Console on port 8084
    tcp-port: "9094"

---
# Profile-specific overrides for the admin service
spring:
  config:
    activate:
      on-profile: "dev-pg"
  sql:
    init:
      mode: always # Admin service always initializes schema in dev-pg
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql