apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-all
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
    compression.type: lz4
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-selected
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000 # 7 days
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-all.DLT
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1 # A single partition is often sufficient for a DLT
  replicas: 3
  config:
    retention.ms: 1209600000 # 14 days retention for analysis
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-selected.DLT
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1 # A single partition is often sufficient for a DLT
  replicas: 3
  config:
    retention.ms: 1209600000 # 14 days retention for analysis
    cleanup.policy: compact