apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-all
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: delete
    compression.type: lz4
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-selected
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: delete
---
# **NEW TOPIC DEFINITION**
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-group
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-all.DLT
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 1209600000
    cleanup.policy: compact
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-selected.DLT
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 1209600000
    cleanup.policy: compact
---
# **NEW DLT TOPIC DEFINITION**
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: broadcast-events-group.DLT
  namespace: kafka-system
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 1209600000
    cleanup.policy: compact