# broadcast-microservice/k8s/base/kustomization.yml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: broadcast-system

# ADD THIS SECTION to create a ConfigMap from the alerts file
configMapGenerator:
- name: broadcast-alerts-config
  files:
  - broadcast-alerts.yml

resources:
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - configmap.yaml
  - network-policy.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pod-disruption-budget.yaml
  - kafka/kafka-topic.yaml
  - prometheus-config.yaml
  - postgres/postgres-pvc.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  # The 'broadcast-alerts.yml' line has been removed from here