apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: broadcast-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.73.0
          ports:
            - name: otlp-grpc
              containerPort: 4317
            - name: ui-http
              containerPort: 16686