# file: k8s/base/kafka-simple/kafka-topics-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-script
  namespace: broadcast-system
data:
  create-kafka-topics.sh: |
    #!/bin/bash
    # This script is for a multi-cluster Kubernetes environment.
    # It's designed to be run from within the cluster.
    
    # This should be the address of your Kafka service within the Kubernetes cluster.
    KAFKA_BROKERS="kafka-service.broadcast-system.svc.cluster.local:9092"

    # --- Wait for Kafka to be ready ---
    echo "Waiting for Kafka broker at $KAFKA_BROKERS to be ready..."
    # Use a loop with kafka-topics to check for connectivity.
    until kafka-topics --bootstrap-server $KAFKA_BROKERS --list 
    do
      echo "Kafka not ready, sleeping for 5 seconds..."
      sleep 5
    done
    echo "Kafka is ready!"
    #--- Create Singleton Topics ---
    ORCHESTRATION_TOPIC="broadcast-orchestration"
    ORCHESTRATION_DLT="${ORCHESTRATION_TOPIC}-dlt"
    
    echo "--- Creating Singleton Topics ---"
    kafka-topics --bootstrap-server $KAFKA_BROKERS --create --if-not-exists --topic $ORCHESTRATION_TOPIC --partitions 1 --replication-factor 3
    kafka-topics --bootstrap-server $KAFKA_BROKERS --create --if-not-exists --topic $ORCHESTRATION_DLT --partitions 1 --replication-factor 3
    
    # --- DELETED: The section for creating pod-specific worker topics has been removed ---

    echo "--- Topic creation script finished successfully. ---"