apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: broadcast-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx-proxy
        image: broadcast-nginx:1.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
        env:
        - name: NGINX_ENV
          value: "prod"
        - name: ADMIN_BACKEND_URL
          value: "https://broadcast-admin-service:8081"
        - name: USER_BACKEND_URL
          value: "https://broadcast-user-service:8082"
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/nginx/certs
          readOnly: true
      volumes:
      - name: ssl-certs
        secret:
          secretName: nginx-ssl-secret