# This Kustomization is for the 'development' environment.
# It uses the 'base' configuration and applies specific patches.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: development

patches:
  - path: admin-deployment-patch.yaml
    target:
      kind: Deployment
      name: broadcast-admin-service
  - path: user-statefulset-patch.yaml
    target:
      kind: StatefulSet
      name: broadcast-user-service