# Patches for the user service deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcast-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcast-user-service
  template:
    spec:
      containers:
        - name: broadcast-user-service
          resources:
            limits:
              memory: "2Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev-pg"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/broadcastdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "cGFzc3dvcmQ="
            - name: SPRING_SQL_INIT_MODE
              value: "always"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1g -XX:+UseG1GC"
            - name: LOGGING_FILE_NAME
              value: ""
            - name: MANAGEMENT_TRACING_ENABLED
              value: "false"