spring:
  config:
    import: "classpath:shared-config.yml"
  application:
    name: broadcast-user-service # User service name
  # User service should not re-initialize the schema
  sql:
    init:
      mode: never

server:
  port: 8082 # User service port
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystore.p12"
    key-store-password: "password"
    key-alias: "netty"

# Log file name is service-specific
logging:
  file:
    name: logs/broadcast-user-service.log

# Resilience4j Rate Limiter is specific to the user service's SSE connect endpoint
resilience4j:
  ratelimiter:
    instances:
      sseConnectLimiter:
        limitForPeriod: 500
        limitRefreshPeriod: 1m
        timeoutDuration: 2s
        registerHealthIndicator: true

# Custom properties unique to the user service
broadcast:
  service:
    name: broadcast-user-service
  h2-console:
    web-port: "8085" # User H2 Console on port 8085
    tcp-port: "9095"
  kafka:
    consumer:
      # Consumer group is specific to the user service
      group-orchestration: "broadcast-orchestration-group"

---
# Profile-specific overrides for the user service
spring:
  config:
    activate:
      on-profile: "dev-pg"
  sql:
    init:
      mode: never # User service never initializes the schema