server:
  port: 8082 # User service port
  shutdown: graceful
  netty:
    worker:
      thread-name-prefix: "http-nio-" # Custom prefix for web threads
  http2:
    enabled: true
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystore.p12"
    key-store-password: "password"
    key-alias: "netty"

spring:
  application:
    name: broadcast-user-service # User service name
  threads:
    virtual:
      enabled: true

  # --- SHARED CONFIGURATIONS ---
  datasource:
    url: jdbc:h2:~/broadcast-system/broadcastdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: false
      path: /h2-console

  # SQL Initialization for schema and data
  sql:
    init:
      mode: never
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    # Consumer configuration is critical for this service
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # group-id: "broadcast-group-#{environment.getProperty('POD_NAME', T(java.util.UUID).randomUUID().toString())}"
      auto-offset-reset: earliest
      properties:
        '[spring.json.trusted.packages]': "*"
        '[max.poll.records]': 500
        '[fetch.max.wait.ms]': 1000
    listener:
      ack-mode: MANUAL_IMMEDIATE
      concurrency: 3

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# Management and Monitoring Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,ratelimiters,redis-cache-stats
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      validate-group-membership: false
      group:
        readiness:
          include: db,kafka,redis
        liveness:
          include: ping

# Logging Configuration
logging:
  level:
    '[com.example.broadcast]': INFO
    '[org.springframework.kafka]': WARN
    '[org.springframework.web]': INFO
    '[org.springframework.jdbc]': INFO
    '[io.github.resilience4j]': INFO
    '[org.apache.kafka.clients.admin.AdminClientConfig]': WARN
    '[org.apache.kafka.clients.consumer.ConsumerConfig]': WARN
    '[org.apache.kafka.clients.producer.ProducerConfig]': WARN
    '[org.apache.kafka.common.metrics]': WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/broadcast-user-service.log

# Resilience4j Configuration
resilience4j:
  ratelimiter:
    instances:
      sseConnectLimiter:
        limitForPeriod: 500
        limitRefreshPeriod: 1m
        timeoutDuration: 2s
        registerHealthIndicator: true

# --- CUSTOM PROPERTIES ---

broadcast:
  h2-console:
    web-port: "8085" # Admin H2 Console on port 8085
    tcp-port: "9095"
  sse:
    timeout: 300000
    heartbeat-interval: 30000
  # Redis Cache Configuration
  cache:
    user-connections:
      maximum-size: 50000
      expire-after-access: PT1H
    user-messages:
      maximum-size: 100000
      expire-after-write: PT24H
    pending-events:
      maximum-size: 50000
      expire-after-write: PT6H

  # Database Configuration
  db:
    batch-size: 1000
    connection-pool-size: 50

  # Kafka Configuration
  kafka:
    topic:
      name-orchestration: broadcast-orchestration
      name-worker-prefix: broadcast-user-service
      partitions: 1
      replication-factor: 1
    consumer:
      group-orchestration: "broadcast-orchestration-group"
      group-worker: "broadcast-worker-group"
      # group-dlt: "broadcast-dlt-group" # Included for consistency, though not used by a listener in this service
    retry:
      max-attempts: 3
      backoff-delay: 1000

---
# PostgreSQL-specific profile for local development
spring:
  config:
    activate:
      on-profile: "dev-pg"
  datasource:
    url: jdbc:postgresql://localhost:5432/broadcastdb?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver # Explicitly set the PostgreSQL driver
    username: user
    password: password
    hikari:
      max-lifetime: 1800000 # 30 minutes
      maximum-pool-size: 50 # Set an explicit max size
      data-source-properties:
        serverTimezone: UTC
  sql:
    init:
      mode: never    