# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: broadcast-system

configMapGenerator:
- name: broadcast-alerts-config
  files:
  - broadcast-alerts.yaml

resources:
  # Core Application
  - namespace.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - configmap.yaml
  - network-policy.yaml
  - admin-deployment.yaml
  - user-deployment.yaml
  - cluster-a-configmap.yaml
  - admin-service.yaml
  - user-service.yaml
  - hpa.yaml
  - pod-disruption-budget.yaml

  # Dependencies
  - postgres/postgres-pvc.yaml
  - postgres/postgres-secret.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - kafka-simple/zookeeper-service.yaml
  - kafka-simple/zookeeper-deployment.yaml
  - kafka-simple/kafka-service.yaml
  - kafka-simple/kafka-deployment.yaml
  - redis/redis-deployment.yaml
  - redis/redis-service.yaml
  - nginx/nginx-secret.yaml
  - nginx/nginx-deployment.yaml
  - nginx/nginx-service.yaml