apiVersion: v1
kind: Service
metadata:
  name: broadcast-service
  namespace: broadcast-system
  labels:
    app: broadcast-microservice
    service: broadcast-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: api
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: broadcast-microservice
  # sessionAffinity: ClientIP
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 3600